import type { Metadata } from 'next'
import Link from 'next/link'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Breadcrumbs from '../components/Breadcrumbs'
import { site } from '@/lib/config'

export const metadata: Metadata = { title: 'Free Budget Spreadsheet: Monthly Income and Expenses', description: 'Download a free CSV budget spreadsheet for monthly income, bills, flexible spending, savings, and debt payments.', alternates: { canonical: `${site.url}/free-budget-spreadsheet` } }

export default function SpreadsheetPage() { return <><Header /><main id="main"><section className="tool-hero compact"><div className="container narrow"><Breadcrumbs items={[{label:'Home',href:'/'},{label:'Free Budget Spreadsheet'}]} /><span className="eyebrow">Free editable CSV</span><h1>Free monthly budget spreadsheet</h1><p>Download a clean starter spreadsheet that opens in Excel, Google Sheets, Apple Numbers, and most spreadsheet apps.</p><div className="hero-cta left"><a href="/budgetloom-monthly-budget.csv" download className="btn btn-primary btn-lg">Download spreadsheet</a><Link href="/monthly-budget-worksheet" className="btn btn-ghost btn-lg">See an example</Link></div></div></section><section className="section"><div className="container narrow article-body"><h2>What the spreadsheet tracks</h2><ul><li>Planned and actual take-home income</li><li>Housing, utilities, groceries, transportation, and other needs</li><li>Flexible wants and personal spending</li><li>Savings, sinking funds, and debt payments</li><li>Monthly totals and money remaining</li></ul><h2>How to use it</h2><ol><li>Download the CSV and open it in your preferred spreadsheet app.</li><li>Save a working copy before editing.</li><li>Replace the example categories and enter planned amounts.</li><li>Add actual spending during a short weekly check-in.</li><li>Use the difference column to improve the following month.</li></ol><p>CSV files do not preserve formulas across every app, so this version prioritizes compatibility. Add formulas in your preferred software, or use our <Link href="/budget-calculator">online budget calculator</Link> for automatic totals.</p></div></section></main><Footer /></> }
