import type { Metadata } from 'next'
import Link from 'next/link'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Breadcrumbs from '../components/Breadcrumbs'
import BudgetCalculator from '../components/BudgetCalculator'
import { site } from '@/lib/config'

export const metadata: Metadata = { title: 'Free Budget Calculator: Plan Your Monthly Spending', description: 'Use this free monthly budget calculator to compare income, needs, wants, savings, and debt payments using a flexible 50/30/20 starting point.', alternates: { canonical: `${site.url}/budget-calculator` }, openGraph: { title: 'Free Monthly Budget Calculator', description: 'Calculate a realistic monthly budget from your take-home income.', url: `${site.url}/budget-calculator`, type: 'website' } }

export default function BudgetCalculatorPage() {
  const schema = { '@context': 'https://schema.org', '@type': 'WebApplication', name: 'BudgetLoom Monthly Budget Calculator', applicationCategory: 'FinanceApplication', operatingSystem: 'Any', url: `${site.url}/budget-calculator`, offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' } }
  return <><Header /><main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><section className="tool-hero compact"><div className="container narrow"><Breadcrumbs items={[{ label: 'Home', href: '/' }, { label: 'Budget Calculator' }]} /><span className="eyebrow">Free interactive tool</span><h1>Monthly budget calculator</h1><p>See where your take-home income is going and whether your current plan leaves money available—or asks you to spend more than you earn.</p></div></section><section className="section"><div className="container narrow"><BudgetCalculator /><div className="article-body tool-copy"><h2>How to calculate your monthly budget</h2><p>Use take-home income, not gross salary. Add the amount you expect to receive after taxes, insurance, retirement deductions, and other payroll deductions.</p><p>Group expenses into needs, wants, and savings or debt payments. The calculator shows the percentage of income assigned to each group and the amount left after your plan.</p><h2>What if the result is negative?</h2><p>A negative result means the plan currently costs more than your expected income. Check flexible categories first, but do not pretend essential bills are smaller than they really are. A useful budget reflects reality.</p><h2>Is 50/30/20 required?</h2><p>No. The guideline suggests up to 50% for needs, 30% for wants, and 20% for savings and additional debt payments. Housing costs, income, family size, and location can make different percentages more realistic.</p></div><div className="callout"><h2>Save your plan on paper</h2><p>Download the free monthly template and copy your calculator totals into it.</p><Link href="/free-budget-template" className="btn btn-primary">Get the free budget template</Link></div></div></section></main><Footer /></>
}
